server:
    port: 8100
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/episodedb
      username: root
      password: 11101996
  jpa:
      show-sql: true

build:
  version: 1.0

friends:
  message: "Welcome to The Friends related APIs"
  contactDetails:
    name: "Joey Tribbiani"
    email: "joey@friends.com"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
