spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/episodes

build:
  version: 1.0

got:
  message: "Welcome to The Game Of Thrones related APIs"
  contactDetails:
    name: "Jon Snow"
    email: "jon@got.com"
