spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/episodes

build:
  version: 1.0

got:
  message: "Welcome to The Game Of Thrones related APIs"
  contactDetails:
    name: "Jon Snow"
    email: "jon@got.com"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
