spring:
  datasource:
      url: jdbc:mysql://localhost:3306/episodedbfdfgdgd
      username: root
      password: 11101996
build:
  version: 3.0

office:
  message: "Welcome to The Office(US) related PROD APIs"
  contactDetails:
    name: "Micheal Scott"
    email: "micheal@office.com"
